---
kind: pipeline
type: docker
name: dot-tmux

platform:
  os: linux
  arch: amd64

steps:
- name: shellcheck-ksh
  image: koalaman/shellcheck-alpine:stable
  commands:
  - shellcheck --shell ksh -S warning .ksh/*

- name: shellcheck-bash
  image: koalaman/shellcheck-alpine:stable
  commands:
  - shellcheck --shell bash -S warning .bash/*

- name: tmux-conf-check
  image: alpine:latest
  # tmux doesn't have a built in config check. Below we pass 'exit' to tmux Control Mode, grep for any config-errors, and then reverse the grep return value.
  # Reversing the grep error code is required as grep returns 0 when text is found, and using -v inverts the whole grep output, not the return code.
  commands:
  - apk add tmux
  - if exit | tmux -f .config/tmux/tmux.conf -C | grep "%config-error"; then return 1; else return 0; fi
