#!/usr/bin/env bash

if command -v tmux > /dev/null 2>&1; then
  if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p /.tmux/plugins/ > /dev/null 2>&1
    git clone -q https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    ~/.tmux/plugins/tpm/bin/install_plugins > /dev/null 2>&1
  fi
fi
