#!/usr/bin/env bash

if command -v tmux > /dev/null 2>&1; then
  alias tmux-update-plugins='~/.tmux/plugins/tpm/bin/update_plugins all'
  alias tmux-install-plugins='~/.tmux/plugins/tpm/bin/install_plugins'
fi
