#!/usr/bin/env zsh

if (`which tmux >/dev/null 2>&1`); then
  alias tmux-update-plugins='~/.tmux/plugins/tpm/bin/update_plugins all'
  alias tmux-update-plugins='~/.tmux/plugins/tpm/bin/install_plugins'
fi
