#!/usr/bin/env zsh

# check for tmux being installed, if it is, try to reattach to existing session>
if [ $(whence -p tmux) ]; then
    # if no session is started, start a new session
    test -z ${TMUX} && (tmux attach || tmux new-session)

    # when quitting tmux, try to attach
    while test -z ${TMUX}; do
        tmux attach || break
    done
fi
