#!/bin/zsh

if hash "tmux" 2>/dev/null; then
  if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p /.tmux/plugins/ > /dev/null 2>&1
    git clone -q https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    ~/.tmux/plugins/tpm/bin/install_plugins > /dev/null 2>&1
  fi
fi
