#!/usr/bin/env ksh

# verify tmux is available
if [ "$(whence -p tmux)" ]; then
  # verify we are not nesting tmux
  if test -z "${TMUX}"; then
    # '-A' makes new-session behave like attach-session if 'main' already exists, otherwise it creates the 'main' session
    tmux new-session -A -s 0
  fi
fi

